import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.css";

import NavigationBar from "@/components/molecules/NavigationBar";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        <NavigationBar
          menus={[
            { label: "channelName", props: { href: "#" } },
            { label: "Home", props: { href: "/" } },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
